name: UT

on:
  push:
    branches: [ halium-10.0 ]
  pull_request:
    branches: [ halium-10.0 ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      - name: Building...
        run: |
          sudo apt update
          sudo apt install android-tools-mkbootimg bc build-essential ca-certificates cpio curl git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          ./build.sh -b bd
          ./build/prepare-fake-ota.sh out/device_olives.tar.xz ota
          ./build/system-image-from-ota.sh ota/ubuntu_command out
     - name: Uploading...
       uses: actions/upload-artifact@v3
         with:
           name: my-artifact
           path: path/to/artifact/
